// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPvaRZd8TTyfu-r1yvIUCpcW4Madu3W5U',
    appId: '1:375923918429:web:4681b131fdf35ad0dfefb4',
    messagingSenderId: '375923918429',
    projectId: 'almuhafiz-25',
    authDomain: 'almuhafiz-25.firebaseapp.com',
    storageBucket: 'almuhafiz-25.firebasestorage.app',
    measurementId: 'G-QK2FT8SHWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6QhJTLc_otxjeMszxAitqUGYw2NIeVY',
    appId: '1:375923918429:android:e1ddd1637f3c7255dfefb4',
    messagingSenderId: '375923918429',
    projectId: 'almuhafiz-25',
    storageBucket: 'almuhafiz-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHGGBwj7UjhUVmqkWfuRfW6_zvYIhHek',
    appId: '1:375923918429:ios:7d104eda92be6dd0dfefb4',
    messagingSenderId: '375923918429',
    projectId: 'almuhafiz-25',
    storageBucket: 'almuhafiz-25.firebasestorage.app',
    iosClientId: '375923918429-n2nfh0326cpq51e8i2ssafd03brd599g.apps.googleusercontent.com',
    iosBundleId: 'com.example.almuhafizTeachers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHGGBwj7UjhUVmqkWfuRfW6_zvYIhHek',
    appId: '1:375923918429:ios:7d104eda92be6dd0dfefb4',
    messagingSenderId: '375923918429',
    projectId: 'almuhafiz-25',
    storageBucket: 'almuhafiz-25.firebasestorage.app',
    iosClientId: '375923918429-n2nfh0326cpq51e8i2ssafd03brd599g.apps.googleusercontent.com',
    iosBundleId: 'com.example.almuhafizTeachers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPvaRZd8TTyfu-r1yvIUCpcW4Madu3W5U',
    appId: '1:375923918429:web:91d28b2ee96f1374dfefb4',
    messagingSenderId: '375923918429',
    projectId: 'almuhafiz-25',
    authDomain: 'almuhafiz-25.firebaseapp.com',
    storageBucket: 'almuhafiz-25.firebasestorage.app',
    measurementId: 'G-F8N2GDYZ7T',
  );
}
