const Map<String, String> enUs = {

  "requiredField": "This field is required",
  "invalidEmail": "Please enter a valid email address",
  "noSpacesInEmail": "Email must not contain spaces",
  "invalidPhone": "Enter a valid phone number",
  "enterLongerText": "Enter a longer text",
  "enterAge": "Please enter your age",
  "enterValidNumber": "Please enter a valid number",
  "ageRange": "Age must be between 12 and 99",
  "passwordsNotMatch": "Confirmation password does not match",
  "textTooLong140": "Enter text shorter than 140 characters",
  "textTooLong90": "Enter text shorter than 90 characters",
  "textTooLong60": "Enter text shorter than 60 characters",
  "maritalStatusSingleMale": "Single",
  "maritalStatusMarriedMale": "Married",
  "maritalStatusDivorcedMale": "Divorced",
  "maritalStatusWidowedMale": "Widowed",
  "maritalStatusSingleFemale": "Single (female)",
  "maritalStatusMarriedFemale": "Married (female)",
  "maritalStatusDivorcedFemale": "Divorced (female)",
  "maritalStatusWidowedFemale": "Widowed (female)",
  "genderMale": "Male",
  "genderFemale": "Female",
  "convertedTimeHour": "hour",
  "convertedTimeHours": "hours",
  "convertedTimeMinute": "minute",
  "convertedTimeMinutes": "minutes",
  "convertedTimeAnd": "and",
  "unexpectedErrorTryAgain": "An unexpected error occurred. Please try again.",
  "onboardingTitle1": "Start with the Quran",
  "onboardingTitle2": "Learn and Memorize Anytime",
  "onboardingTitle3": "Reflect to Live the Meaning",
  "onboardingDescription1": "Begin your journey with Al-Muhafiz to learn, memorize, and live by the words of Allah.",
  "onboardingDescription2": "Audio and video sessions with elite teachers to learn recitation and Tajweed.",
  "onboardingDescription3": "Discover meanings, answer questions, and let the Quran leave its impact on you and those around you.",
  "follow": "Continue",
  "skip": "Skip",
  "getStarted": "Get Started",
  "welcomeText": "Welcome to",
  "startSession": "Start Session",
  "enterFreeSession": "Enter your free session",
  "bookNow": "Book Now",
  "suggestedTeachers": "Suggested teachers for you",
  "seeMore": "See More",
  "yourDailySchedule": "Your Daily Schedule",
  "firstSchedule": "First Schedule",
  "nextSession": "Next Session:",
  "addSchedule": "Add Schedule",
  "now": "Now",
  "ago": "Ago",
  "seconds": "Seconds",
  "minute": "Minute",
  "minutes": "Minutes",
  "hour": "Hour",
  "hours": "Hours",
  "day": "Day",
  "days": "Days",
  "week": "Week",
  "weeks": "Weeks",
  "month": "Month",
  "months": "Months",
  "year": "Year",
  "years": "Years",
  "createNewAccount": "Create New Account",
  "email": "Email",
  "password": "Password",
  "confirmPassword": "Confirm Password",
  "passwordConfirmation": "Password Confirmation",
  "agreeTerms": "I agree to the Terms of Use and Privacy Policy",
  "createAccount": "Create Account",
  "or": "Or",
  "alreadyHaveAccount": "Already have an account?",
  "loginNow": "Login Now",
  "iAgree": "I agree to",
  "termsOfUse": "Terms of Use",
  "and": "and",
  "privacyPolicy": "Privacy Policy",
  "login": "Login",
  "wrongPassword": "The password is incorrect, please retype it",
  "forgotPassword": "Forgot Password?",
  "signIn": "Sign In",
  "noAccount": "Don't have an account?",
  "createAccountNow": "Create an account now",
  "passwordMustHaveLetter": "Password must contain at least one letter",
  "passwordMustHaveSymbol": "Password must contain at least one symbol",
  "changePassword": "Change Password",
  "newPassword": "New Password",
  "confirmNewPassword": "Confirm Password",
  "confirm": "Confirm",
  "codeNotSent": "Didn't receive the code?",
  "resendCode": "Resend Code",
  "sentCodeToEmail": "We have sent a 6-digit code to your email, please verify it and re-enter it in the following fields",
  "continueTxt": "Continue",
  "onlyNumbersAllowed": "Only numbers are allowed",
  "passwordChanged": "Password has been changed",
  "emailConfirmation": "Email confirmation",
  "emailConfirmed": "Your email has been confirmed",
  "completeYourData": "Complete your data",
  "enterPreferredName": "Enter the name you want to be called",
  "enterNameHere": "Enter your name here",
  "yourAge": "How old are you",
  "enterAgeHere": "Enter your age here",
  "yourGender": "What is your gender",
  "male": "Male",
  "female": "Female",
  "general": "General",
  "selectNovelAndPath": "Select Recitation and path",
  "recitation": "Recitation",
  "path": "Path",
  "home": "Home",
  "teachers": "Teachers",
  "questions": "Questions",
  "sessions": "Sessions",
  "profile": "Profile",
  "notifications": "Notifications",
  "all": "All",
  "read": "Read",
  "bookLater": "Book a later session",
  "inSession": "In session",
  "onlineNow": "Online now",
  "notAvailable": "Not available",
  "teacherName": "Teacher Name",
  "online": "Online",
  "favorites": "Favorites",
  "teacher": "Teacher",
  "schedule": "Schedule",
  "teacherBio": "Teacher biography",
  "quranReadings": "Qur’anic recitations",
  "permissions": "Ijazat",
  "reviews": "Comments",
  "saudiArabia": "Saudi Arabia",
  "unitedArabEmirates": "United Arab Emirates",
  "egypt": "Egypt",
  "kuwait": "Kuwait",
  "qatar": "Qatar",
  "bahrain": "Bahrain",
  "oman": "Oman",
  "jordan": "Jordan",
  "lebanon": "Lebanon",
  "syria": "Syria",
  "iraq": "Iraq",
  "morocco": "Morocco",
  "algeria": "Algeria",
  "tunisia": "Tunisia",
  "libya": "Libya",
  "sudan": "Sudan",
  "yemen": "Yemen",
  "palestine": "Palestine",
  "unitedStates": "United States",
  "unitedKingdom": "United Kingdom",
  "canada": "Canada",
  "france": "France",
  "germany": "Germany",
  "italy": "Italy",
  "spain": "Spain",
  "turkey": "Turkey",
  "india": "India",
  "china": "China",
  "japan": "Japan",
  "southKorea": "South Korea",
  "brazil": "Brazil",
  "russia": "Russia",
  "australia": "Australia",
  "monday": "Monday",
  "tuesday": "Tuesday",
  "wednesday": "Wednesday",
  "thursday": "Thursday",
  "friday": "Friday",
  "saturday": "Saturday",
  "sunday": "Sunday",
  "bookSession": "Book Session",
  "selectDayTime": "Select day and time",
  "sessionTime": "Session time",
  "sessionType": "Session type",
  "video": "Video",
  "audio": "Audio",
  "completeBooking": "Complete booking",
  "sessionStartingSoon": "The session will start shortly",
  "pleaseWait": "Please wait",
  "saveTeacher": "You can save this teacher and book with them again anytime if you like 💚",
  "rateTeacher": "Rate the teacher",
  "writeReview": "Write your review about the teacher",
  "sendRating": "Send Rating",
  "joinSession": "Join the session",
  "time": "Time",
  "groupSession": "Group session",
  "individualSession": "Individual session",
  "privateSession": "Private session",
  "hafsAnAsim": "Hafs 'an Asim",
  "warshAnNafi": "Warsh 'an Nafi",
  "qalunAnNafi": "Qalun 'an Nafi",
  "adDuriAnAbiAmr": "Ad-Duri 'an Abi Amr",
  "joinOnTime": "Joining at the scheduled time",
  "sessionNotStartedYet": "The session time has not arrived yet",
  "pleaseJoinAt": "Please join at",
  "addToCalendar": "Add to calendar",
  "done": "Done",
  "totalAttendance": "Total attendance",
  "allowedAttendance": "Allowed attendance",
  "juz": "Juz",
  "hizb": "Hizb",
  "surah": "Surah",
  "fromAyah": "From Ayah",
  "toAyah": "To Ayah",
  "scheduleTitle": "Schedule title",
  "enterScheduleTitle": "Enter schedule title",
  "selectStartDate": "Select schedule start date",
  "scheduleStartDate": "Schedule start date",
  "weekDays": "Week days",
  "sessionsPerDay": "Number of sessions per day",
  "oneSession": "One session",
  "twoSessions": "Two sessions",
  "threeSessions": "Three sessions",
  "preferredTimeForFirstSession": "Preferred time for the first session",
  "nextStep": "Next step",
  "addTrackToSchedule": "Add the track you want in the schedule",
  "tilawahCorrection": "Tilawah correction",
  "telqeen": "Telqeen",
  "review": "Review",
  "iqraaIjaza": "Iqra’a & Ijaza",
  "hifzAndRevision": "Memorization & revision",
  "chooseScheduleOrganization": "Do you want to organize this schedule by Juz, Surah, or Pages?",
  "page": "Page",
  "pages": "Pages",
  "riwayahType": "Riwayah type",
  "type": "Type",
  "selectLearningObjectives": "Select learning objectives",
  "learningObjective": "Learning objective",
  "tajweedRules": "Tajweed rules",
  "hiddenMistakesCorrection": "Correct hidden mistakes",
  "clearMistakesCorrection": "Correct clear mistakes",
  "fromSurah": "From surah",
  "toSurah": "To surah",
  "scheduleDetails": "Schedule details",
  "updateSchedule": "Update schedule",
  "editSchedule": "Edit schedule",
  "deleteSchedule": "Delete schedule",
  "readingTypeLabel": "Reading type",
  "pagesPerSession": "Pages per session",
  "confirmUpdatePlan": "Are you sure you want to update your plan?",
  "planStartDateReset": "The start date of the plan will be reset from today",
  "noKeepIt": "No, keep it",
  "yesSure": "Yes, I’m sure",
  "from": "From",
  "to": "To",
  "yourName": "Your Name",
  "settings": "Settings",
  "language": "Language",
  "sessionRecording": "Session recording",
  "support": "Support",
  "aboutUs": "About us",
  "shareApp": "Share the app",
  "deleteAccount": "Delete account",
  "confirmDeleteAccount": "Are you sure you want to delete your account?",
  "deleteAccountWarning": "Your account will be permanently deleted along with all your data and sessions",
  "deleteYes": "Yes, delete my account",
  "deleteNo": "No, keep my account",
  "enterNewPassword": "Enter a new password",
  "subscription": "Subscription",
  "editProfile": "Edit profile",
  "mySessions": "My sessions",
  "learningPath": "Learning path and options",
  "manageSchedules": "Manage schedules",
  "paymentCards": "Payment cards and info",
  "paymentHistory": "Payment history",
  "volunteerTeacher": "Volunteer as a teacher",
  "saveChanges": "Save changes",
  "dailySchedule": "Your daily schedule",
  "currentMonthSessions": "Current month sessions",
  "primaryCard": "Primary card",
  "paymentCard": "Payment card",
  "addPaymentCard": "Add payment card",
  "cardHolderName": "Name on card",
  "creditCardInfo": "Credit card information",
  "arabic": "Arabic",
  "english": "English",
  "student_level_beginner_title": "Seeker of Light",
  "student_level_committed_title": "Lover of the Quran",
  "student_level_advanced_title": "Mindful Remembrancer",
  "student_level_expert_title": "Bearer of Light",
  "student_level_master_title": "Carrier of the Quran",
  "student_level_beginner_description": "He has started his journey of memorizing the Holy Quran.",
  "student_level_committed_description": "He consistently memorizes and reviews regularly.",
  "student_level_advanced_description": "He has mastered recitation and Tajweed and is close to completion.",
  "student_level_expert_description": "He has memorized half of the Quran or more with proficiency.",
  "student_level_master_description": "He has fully memorized the Holy Quran and become a role model for others.",
  "upcoming" : "Upcoming",
  "errorBuildScreen": "Sorry, something went wrong while loading this screen",
  "internetConnectionError": "Internet connection error",
  "internetConnectionErrorMessage": "Please check your internet connection and try again.",
  "tryAgain": "Try again",
  "am" : "AM",
  'pm' : "PM",
  "booked" : "Booked",
  "today": "Today",
  "tomorrow": "Tomorrow",
  "dayAfterTomorrow": "Day after tomorrow",
  "m" : "M",
  "selectSessionTimeFirst": "Please select the session time first",
  "success" : "success",
  "error" : "error",
  "warning" : "warning",
  "slotBookedFailed": "Slot booking failed",
  "slotBookedSuccessfully": "Slot booked successfully.\nThe tutor will be notified that you booked the session.",
  "ok" : "OK",
  "sessionDetails": "Session details",
  "accountRegisteredAsTutor": "This account is already registered as a tutor and cannot be used to log in to the user app. Please use a different account.",
  "unknownError": "An unexpected error occurred",
  "emailRegisteredSuccessfully": "Your email has been registered successfully",
  "completeYourInformation": "Complete your information",
  "mustAcceptTerms": "You must accept the terms and conditions",
  "noInternetConnection" : "Unable to connect to the internet at the moment",
  "noInternetConnectionMessage" : "Please check your internet connection and try again.",
  "refresh" : "Refresh",
  "loginFirst": "One step away!",
  "loginFirstBody": "Log in now to enjoy all features and complete this step effortlessly.",
  "cancel": "Cancel",
  "loginAsGuest": "Continue as Guest",
  "logout": "Log out",
  "logoutBody": "You can log back in at any time.",
  "updateAvailable": "We've added improvements and new features for a better experience. Update the app now and enjoy what's new.",
  "updateNow": "Update Now",
  "unexpectedError": "An unexpected error occurred. We're working to fix it, please try again shortly.",
  "tapToClose": "Tap to close",
  "noTeachersAvailable": "No teachers are currently available",
  "profileUpdatedSuccessfully": "Profile updated successfully",
  "saveEditing": "Save Editing",
  "leaveYourPhoneNumber": "Contact phone number",
  "writeYourMessage": "Type your message here",
  "send" : "Send",
  "whatsAppNotInstalled": "WhatsApp is not installed",
  "noEmailAppFound": "No email app found",
  "whatsApp" : "WhatsApp",
  "gmail" : "Gmail",
  "phone" : "Phone",
  "message" : "Message",
  "passwordChangedSuccessfully": "Password changed successfully",
  "oldPassword": "Old password",
  "enterOldPassword": "Enter old password",
  "passwordUpdatedSuccessfully": "Password updated successfully",
  "validity": "Validity",
  "free": "Free",
  "plans" : "Plans",
  "inputPaymentInfo" : "Input Payment Info",
  "noPlansFound": "No plans are available for you at the moment",
  "selectedPlanDetails": "Selected plan details",
  "gifts" : "Gifts",
  "useNow": "Use now",
  "notCompletedYet": "Not completed yet",
  "ranking": "Ranking",
  "rankingMessage": "Continue, be among the top seven",
  "continue" : "Continue",
  "noRankingUsers": "Be the first to appear in the ranking",
  "noSessionsYet": "You haven't registered any sessions yet. Start now to make the most of our services.",
  "videoLoadFailed": "Failed to load the video",
  "accountDeleted" : "Account Deleted",
  "accountDeletedAlert": "Please log in again before deleting the account",
  "oldPasswordIncorrect": "The old password is incorrect",
  "weakNewPassword": "The new password is too weak",
  "pleaseLoginAgain": "Please log in again",
  "userNotLoggedIn": "User not logged in",
  "enterYourPasswordForDeleteAccount": "Please enter your password to continue deleting your account",
  "quranCompletionDua": "Dua for completing the Quran",
  "quranCompletionDuaText": "O Allah, have mercy on us through the Quran. Make it for us a guide, a light, a source of guidance and mercy. O Allah, remind us of what we have forgotten from it, teach us what we do not know, and grant us its recitation during the hours of the night and the ends of the day in a manner that pleases You.\n\nO Allah, make the Great Quran the spring of our hearts, the light of our chests, the remover of our sorrows, and the relief of our worries and grief.\n\nO Allah, make us among those who deem lawful what it has made lawful, forbid what it has made forbidden, believe in its clear and allegorical verses, and make it an argument for us, not against us, O Lord of the worlds.\n\nO Allah, grant us to act upon it, to stand by its limits, and make us among the people of the Quran who are Your people and Your chosen ones.\n\nO Allah, raise us in ranks through the Quran, grant us happiness in this world, success in Paradise in the Hereafter, and save us from the Fire.\n\nO Allah, conclude our deeds with righteousness, our lives with happiness, and our final destiny with forgiveness and pleasure.\n\nAnd send Your prayers, peace, and blessings upon our Prophet Muhammad, and upon his family and companions all together.",
  "aboutPlatform" : "We are a platform dedicated to serving the Book of Allah, spreading its meanings, and promoting reflection and correct understanding of the Holy Quran in a simple and contemporary manner suitable for all audiences.\n\nWe strive to provide reliable Quranic content that combines the Quranic text with trusted interpretations, transforming meanings into reflective and interactive questions that help users understand, contemplate, and connect the verses to daily life.\n\nWe believe that the Quran is not only for recitation, but for reflection and action. Therefore, we are committed to:\n\n• Providing questions and answers derived from authentic interpretations.\n• Simplifying meanings without compromising their accuracy.\n• Using modern technology to serve the Holy Quran.\n• Offering a calm and beneficial educational experience.\n\nOur goal is for this project to be a means of bringing hearts closer to the words of Allah, helping in understanding and acting upon them. We ask Allah for acceptance and success.\n\n“[This is] a blessed Book which We have revealed to you, that they might reflect upon its verses.”",
  "chooseOptions": "Choose options"

};